package iut2.forbiddenisland.controller;

public enum RequestType {
	PLAYER_MOVE_AMOUNT,
	CELLS_REACHABLE,
	CELLS_DRYABLE,
	PLAYERS_SENDABLE,
	TREASURES_CLAIMABLE,
	PLAYER_MOVE,
	CELL_DRY,
	PLAYER_SEND,
	PLAYER_CLAIM_TREASURE,
	FLOODING
}
